namespace ColdClimb.Audio{ 
    public enum AudioType{
        None,
        SOUNDTRACK_01,
        SOUNDTRACK_02,
        SOUNDTRACK_03,
        SOUNDTRACK_04,
        SOUNDTRACK_05,
        SOUNDTRACK_06,
        PLAYER_STEP_SNOW_01,
        PLAYER_STEP_SNOW_02,
        PLAYER_STEP_WOOD_01,
        PLAYER_STEP_WOOD_02,
        PLAYER_STEP_STONE_01,
        PLAYER_STEP_STONE_02,
        PLAYER_STEP_STONE_03,
        PLAYER_STEP_STONE_04,
        AMBIENCE_01,
        AMBIENCE_02,
        AMBIENCE_03,
        AMBIENCE_04,
        AMBIENCE_05,
        UI_01,
        UI_02,
        UI_03,
        UI_04,
        ITEM_GLOCK_FIRE,
        ITEM_GLOCK_RELOAD,
        ITEM_GLOCK_EQUIP,
        ITEM_FLASHLIGHT_USE,
        ITEM_FLASHLIGHT_ZOOM_IN,
        ITEM_FLASHLIGHT_ZOOM_OUT
    }
}

